pipeline {
	agent any

	parameters {   
	string( name: 'REQUIREMENT', 
	    defaultValue: '0', 
	    description: 'ID del requerimiento de la forma RQXXXXX')
	string( name: 'COMPONENT',
	    defaultValue: '', 
	    description: 'Por defecto en vacío para que procese todos los componentes, especificar DB, DP, BAR o MQ')
	string( name: 'USER', 
	    defaultValue: '', 
	    description: 'Correo electronico')
	string( name: 'ID_JIRA', 
	    defaultValue: '', 
	    description: 'Identificador ID requerimiento Jira')
	}
	
	environment{
		gitCommit='noCommit'
		gitMessage='noMessage'
		action='noAction'
		requerimiento='noRQ'
		emailTo='noEmail'
	}
	
	stages{
		stage('CLEAN WORKSPACE'){
			steps{
				step([$class: 'WsCleanup'])
			}
		}
		stage('1. Allocate workspace') { 
			steps{
				echo "Valor inicial del requerimiento: "+params["REQUIREMENT"]
				script{
					if (params["REQUIREMENT"] != "0") {
						def extWorkspace = exwsAllocate 'diskpool1'
						node (''){
							def step=1;
							exws(extWorkspace) {
								
								action = params["ACTION"];
								if ((params["COMPONENT"] == '')) {
									action = ""
								}

								step++ 
							}
						}
					}		
				}
			}
		}
		stage('2. Checkout') {
			steps{
				script{
					checkout changelog: false, poll: false,
						scm: [$class : 'GitSCM', branches: [[name: '*/master']],
							  extensions : [[$class: 'SparseCheckoutPaths',
											 sparseCheckoutPaths: [[path: 'MODEL']]]],
							  userRemoteConfigs: [[credentialsId: 'GitHub token ugithub', url: 'https://devops-github.ath.net/esb/requirements-deliverables.git']]]
										
					gitCommit = sh(returnStdout: true, script: 'git rev-parse --short HEAD').trim()
					gitMessage = sh(returnStdout: true, script: 'git log -1 | grep RQ || true').trim()
					gitRequirement=sh(returnStdout: true, script: "git log -1 | grep RQ | sed 's/:.*//'|| true").trim()
					gitEmail=sh(returnStdout: true, script: "git log -1 | grep RQ | cut -d ':' -f2 || true").trim()
					
					step([$class: 'WsCleanup'])
					
					if (params["REQUIREMENT"] != "0") {//si no se especifica se emplea el del commit
						requerimiento=params["REQUIREMENT"]
						emailTo=params["USER"]
					}else{
						requerimiento=gitRequirement
						emailTo=gitEmail
					}
					
					shell('pwd')
					checkout changelog: false, poll: false,
							scm: [$class : 'GitSCM', branches: [[name: '*/master']],
								  extensions : [[$class: 'SparseCheckoutPaths',
												 sparseCheckoutPaths: [[path: 'MODEL'], [path: requerimiento]]]],
								  userRemoteConfigs: [[credentialsId: 'GitHub token ugithub', url: 'https://devops-github.ath.net/esb/requirements-deliverables.git']]]

					echo 'Mensaje de commit: ' + gitMessage
					echo 'Requerimiento: ' + gitRequirement
					echo 'Email: ' + gitEmail
					
					sh('cp MODEL/pom.xml pom.xml')
						
				}
			}
		}
		stage('3. Build') {
			steps{
				script {
					if (gitMessage != ''){
						echo 'Git commit: ' + gitCommit
						def buildNumber = env.BUILD_NUMBER;
						echo 'Build ' + buildNumber
						echo './' + requerimiento + '/MQ/'
						if ((params["COMPONENT"] == '' || params["COMPONENT"] == 'MQ') && fileExists('./' + requerimiento + '/MQ/')) {
							echo 'MQ Artifacts found'
							sh('pwd')
							
							build job: 'DOWNSTREAM-BUILD-MQ-RQ-GITHUB', parameters: [
									[$class: 'StringParameterValue', name: 'REQUIREMENT', value: requerimiento],
									[$class: 'StringParameterValue', name: 'USER', value: emailTo],
									[$class: 'StringParameterValue', name: 'UPSTREAM_BUILD_NUMBER', value: buildNumber],
									[$class: 'StringParameterValue',name: 'SVNVERSION', value: gitCommit],
									[$class: 'StringParameterValue', name: 'ACTION', value: action],
									[$class: 'StringParameterValue', name: 'WS_MASTER', value: workspace]]
									
															}
						if ((params["COMPONENT"] == '' || params["COMPONENT"] == 'DB') && fileExists('./' + requerimiento + '/DB/')) {
							echo 'DB Artifacts found'
							sh('pwd')
							build job: 'DOWNSTREAM-BUILD-DB-RQ-GITHUB', parameters: [
									[$class: 'StringParameterValue', name: 'REQUIREMENT', value: requerimiento],
									[$class: 'StringParameterValue', name: 'USER', value: emailTo],
									[$class: 'StringParameterValue', name: 'UPSTREAM_BUILD_NUMBER', value: buildNumber],
									[$class: 'StringParameterValue', name: 'SVNVERSION', value: gitCommit],
									[$class: 'StringParameterValue', name: 'ACTION', value: action],
									[$class: 'StringParameterValue', name: 'WS_MASTER', value: workspace]]
						}
						if ((params["COMPONENT"] == '' || params["COMPONENT"] == 'BAR') && fileExists('./' + requerimiento + '/BAR/')) {
							echo 'BAR Artifacts found'
							sh('pwd')
							build job: 'DOWNSTREAM-BUILD-BAR-RQ-GITHUB', parameters: [
									[$class: 'StringParameterValue', name: 'REQUIREMENT', value: requerimiento],
									[$class: 'StringParameterValue', name: 'USER', value: emailTo],
									[$class: 'StringParameterValue', name: 'UPSTREAM_BUILD_NUMBER', value: buildNumber],
									[$class: 'StringParameterValue', name: 'SVNVERSION', value: gitCommit],
									[$class: 'StringParameterValue', name: 'ACTION', value: action],
									[$class: 'StringParameterValue', name: 'WS_MASTER', value: workspace]]
						}
						if ((params["COMPONENT"] == '' || params["COMPONENT"] == 'DP') && fileExists('./' + requerimiento + '/DP/')) {
							echo 'DP Artifacts found'
							sh('pwd')
							build job: 'DOWNSTREAM-BUILD-DP-RQ-GITHUB', parameters: [
									[$class: 'StringParameterValue', name: 'REQUIREMENT', value: requerimiento],
									[$class: 'StringParameterValue', name: 'USER', value: emailTo],
									[$class: 'StringParameterValue', name: 'UPSTREAM_BUILD_NUMBER', value: buildNumber],
									[$class: 'StringParameterValue', name: 'SVNVERSION', value: gitCommit],
									[$class: 'StringParameterValue', name: 'ACTION', value: action],
									[$class: 'StringParameterValue', name: 'WS_MASTER', value: workspace]]
						}
					}
				}
			}
		}
	}

post {
        success {
            script {
                try {
			emailext(
				    to: emailTo,
				    subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' REQ:" + requerimiento,
				    body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} Version: ${gitCommit}.${env.BUILD_NUMBER}':</p>
				    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
			    )
                } catch (e) {
			emailext(
				    to: emailTo,
				    subject: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' REQ:" + requerimiento,
				    body: """<p>SUCCESSFUL: Job '${env.JOB_NAME} Version: ${gitCommit}.${env.BUILD_NUMBER}':</p>
				    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>"""
			    )
                }
            }

        }
        failure {
            script {
                try {
		    emailext(
			    to: emailTo,
			    subject: "FAILED: Job '${env.JOB_NAME} [" + rev + "]' REQ:" + requerimiento,
			    body: """<p>FAILED: Job '${env.JOB_NAME} Version: ${gitCommit}.${env.BUILD_NUMBER}':</p>
			    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>""",
			    attachLog: true
		    )
                } catch (e) {
		    emailext(
			    to: emailTo,
			    subject: "FAILED: Job '${env.JOB_NAME} [" + rev + "]' REQ:" + requerimiento,
			    body: """<p>FAILED: Job '${env.JOB_NAME} Version: ${gitCommit}.${env.BUILD_NUMBER}':</p>
			    <p>Check console output at "<a href="${env.BUILD_URL}">${env.JOB_NAME} [${env.BUILD_NUMBER}]</a>"</p>""",
			    attachLog: true
		    )
                }
            }
        } 
    }
}
