/*===================================================================================================
  TIPO: insert
-----------------------------------------------------------------------------------------------------
  DESCRIPCION: 
-----------------------------------------------------------------------------------------------------
  FECHA PLANEADA PRODUCCION: DD/MM/YYYY
-----------------------------------------------------------------------------------------------------
  RESPONSABLE: FABRICA CBIT
-----------------------------------------------------------------------------------------------------
  No. RQ: AAAAA
-----------------------------------------------------------------------------------------------------
  BD AFECTADA: WSRR
-----------------------------------------------------------------------------------------------------
  TABLAS AFECTADAS: MAPPING_CODE
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRUEBAS PT: ORA12IIB10
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRUEBAS QA: ORA12IIB10 
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRODUCCION: ESBCATALOGS  
 -----------------------------------------------------------------------------------------------------
  NOMBRE SERVICIO: BillPaymentPSE
===================================================================================================*/
/*===================================================================================================
  CODIGO FUENTE
===================================================================================================*/

-- ****PRUEBAS TECNICA (PT) Y CALIDAD (QA)****
ALTER SESSION SET CURRENT_SCHEMA=ORA12IIB10;
-- ****PRODUCCIoN (PROD)****
---ALTER SESSION SET CURRENT_SCHEMA=ESBCATALOGS;
--SELECT SUBSTR(HOST_NAME,1,20) SERVIDOR,	sys_context('USERENV', 'DB_NAME') as Base_Datos, SUBSTR(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'),1,20) esquema, SUBSTR(SYS_CONTEXT('USERENV', 'HOST'), 1,20) Nombre_PC, SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'),1,30) Usuario_SO, SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'),1,20) Usuario_BD, TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FECHA	FROM V$INSTANCE;

--*** TRANCODE BillPaymentPSEBillPmt  P_BILLPAYPSEPMT Debito del pago PSE hacia las Entidades

-- Codigos de error Banco Avvillas
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción Exitosa' WHERE BANKID='00010524' AND IFXCODE='0' AND HOSTCODE='0' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción Exitosa' WHERE BANKID='00010524' AND IFXCODE='0' AND HOSTCODE='00' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción Exitosa' WHERE BANKID='00010524' AND IFXCODE='0' AND HOSTCODE='90' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Acceso no autorizado.  Por favor comuníquese con la Entidad' WHERE BANKID='00010524' AND IFXCODE='1420' AND HOSTCODE='1' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. El valor de la transacción es superior al tope máximo establecido.' WHERE BANKID='00010524' AND IFXCODE='2080' AND HOSTCODE='2' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. Excede los límites autorizados.' WHERE BANKID='00010524' AND IFXCODE='3000' AND HOSTCODE='3' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.' WHERE BANKID='00010524' AND IFXCODE='200' AND HOSTCODE='4' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Valor invalido' WHERE BANKID='00010524' AND IFXCODE='1050' AND HOSTCODE='5' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Valor invalido' WHERE BANKID='00010524' AND IFXCODE='1050' AND HOSTCODE='11' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Valor invalido' WHERE BANKID='00010524' AND IFXCODE='1050' AND HOSTCODE='13' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'No es posible procesar la transacción. Comuníquese con la entidad.' WHERE BANKID='00010524' AND IFXCODE='401' AND HOSTCODE='12' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. Cuenta origen inválida. Comuníquese con la entidad.' WHERE BANKID='00010524' AND IFXCODE='2300' AND HOSTCODE='14' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Número de obligación o de factura inválido o no existe.' WHERE BANKID='00010524' AND IFXCODE='1220' AND HOSTCODE='15' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'La factura esta vencida o tiene restricciones de pago' WHERE BANKID='00010524' AND IFXCODE='1400' AND HOSTCODE='16' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Este pago ya fue realizado.' WHERE BANKID='00010524' AND IFXCODE='1380' AND HOSTCODE='17' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.' WHERE BANKID='00010524' AND IFXCODE='2350' AND HOSTCODE='19' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'En este momento no es posible procesar su transacción - Por favor intente más tarde.' WHERE BANKID='00010524' AND IFXCODE='1360' AND HOSTCODE='29' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'En este momento no es posible procesar su transacción - Por favor intente más tarde.' WHERE BANKID='00010524' AND IFXCODE='1360' AND HOSTCODE='30' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'En este momento no es posible procesar su transacción - Por favor intente más tarde.' WHERE BANKID='00010524' AND IFXCODE='1360' AND HOSTCODE='31' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.' WHERE BANKID='00010524' AND IFXCODE='200' AND HOSTCODE='32' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Número de obligación o de factura inválido o no existe.' WHERE BANKID='00010524' AND IFXCODE='1220' AND HOSTCODE='33' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Fondos insuficientes' WHERE BANKID='00010524' AND IFXCODE='2940' AND HOSTCODE='51' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'El número de pagos es inválido. Por favor intente nuevamente.' WHERE BANKID='00010524' AND IFXCODE='3300' AND HOSTCODE='61' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.' WHERE BANKID='00010524' AND IFXCODE='2350' AND HOSTCODE='62' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción rechazada. El valor de la transacción es superior al tope máximo establecido.' WHERE BANKID='00010524' AND IFXCODE='2080' AND HOSTCODE='63' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'La factura esta vencida o tiene restricciones de pago' WHERE BANKID='00010524' AND IFXCODE='1400' AND HOSTCODE='70' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Valor invalido' WHERE BANKID='00010524' AND IFXCODE='1050' AND HOSTCODE='71' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'En este momento no es posible procesar su transacción - Por favor intente más tarde.' WHERE BANKID='00010524' AND IFXCODE='1360' AND HOSTCODE='72' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'En este momento no es posible procesar su transacción - Por favor intente más tarde.' WHERE BANKID='00010524' AND IFXCODE='1360' AND HOSTCODE='73' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'El monto de la obligación  no concuerda con el valor a pagar.' WHERE BANKID='00010524' AND IFXCODE='3040' AND HOSTCODE='74' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'OTP invalida o anulada por reintentos fallidos.  Solicite una nueva OTP.' WHERE BANKID='00010524' AND IFXCODE='1056' AND HOSTCODE='96' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'No es posible procesar la transacción.' WHERE BANKID='00010524' AND IFXCODE='700' AND HOSTCODE='99' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'Transacción en proceso. Por favor verifique mas tarde.' WHERE BANKID='00010524' AND IFXCODE='310' AND HOSTCODE='98' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.' WHERE BANKID='00010524' AND IFXCODE='200' AND HOSTCODE='9091' AND TRANCODE='P_BILLPAYPSEPMT';
UPDATE MAPPING_CODE SET DESC_ERROR_HOM = 'OTP invalida o anulada por reintentos fallidos.  Solicite una nueva OTP.' WHERE BANKID='00010524' AND IFXCODE='1056' AND HOSTCODE='42' AND TRANCODE='P_BILLPAYPSEPMT';


INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1400' ,'10','P_BILLPAYPSEPMT',NULL,'1','La factura esta vencida o tiene restricciones de pago');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'-12','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'20','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','310'  ,'21','P_BILLPAYPSEPMT',NULL,'1','Transacción en proceso. Por favor verifique mas tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'22','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'23','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'24','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'25','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'27','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'28','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'34','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2400' ,'35','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'40','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1600' ,'41','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1055' ,'42','P_BILLPAYPSEPMT',NULL,'1','OTP invalida por vencimiento o anulación.  Solicite una nueva OTP.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'43','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2350' ,'44','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'45','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'46','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','3320' ,'52','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Excede los límites autorizados. Comuníquese con la Entidad');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'53','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'54','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'55','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'56','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'57','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'58','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2300' ,'6','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Cuenta origen inválida. Comuníquese con la entidad.');

INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '2667', 'P_BILLPAYPSEPMT', NULL, '1', 'Error al abrir Cola - Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '2666', 'P_BILLPAYPSEPMT', NULL, '1', 'Error al abrir Cola - Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '300', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente - TimeOut');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', 'env:Server', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', 'env:Client', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '700', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '200', '200', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion - datos inconsistentes. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '400', '400', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5025', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5004', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '710', '710', 'P_BILLPAYPSEPMT', NULL, '1', 'Error en Base de Datos');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '3701', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '3151', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente - TimeOut');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5025', 'P_BILLPAYPSEPMT', NULL, '1', 'Error validacion estructura');

INSERT INTO ACCTTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM ACCTTYPE) + 1, '00010524','6', '6','P_BILLPAYPSEPMT', 'Cuenta Corriente');
UPDATE ACCTTYPE SET DESCRIPTION = 'Cuenta de Ahorros' WHERE BANKID='00010524' AND EPID='1' AND HOSTID='1' AND TRANCODE='P_BILLPAYPSEPMT';

COMMIT;