/*===================================================================================================
  TIPO: insert
-----------------------------------------------------------------------------------------------------
  DESCRIPCION: 
-----------------------------------------------------------------------------------------------------
  FECHA PLANEADA PRODUCCION: DD/MM/YYYY
-----------------------------------------------------------------------------------------------------
  RESPONSABLE: FABRICA CBIT
-----------------------------------------------------------------------------------------------------
  No. RQ: AAAAA
-----------------------------------------------------------------------------------------------------
  BD AFECTADA: WSRR
-----------------------------------------------------------------------------------------------------
  TABLAS AFECTADAS: MAPPING_CODE
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRUEBAS PT: ORA12IIB10
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRUEBAS QA: ORA12IIB10 
-----------------------------------------------------------------------------------------------------
  ESQUEMA PRODUCCION: ESBCATALOGS  
 -----------------------------------------------------------------------------------------------------
  NOMBRE SERVICIO: BillPaymentPSE
===================================================================================================*/
/*===================================================================================================
  CODIGO FUENTE
===================================================================================================*/

-- ****PRUEBAS TECNICA (PT) Y CALIDAD (QA)****
ALTER SESSION SET CURRENT_SCHEMA=ORA12IIB10;
-- ****PRODUCCIoN (PROD)****
---ALTER SESSION SET CURRENT_SCHEMA=ESBCATALOGS;
--SELECT SUBSTR(HOST_NAME,1,20) SERVIDOR,	sys_context('USERENV', 'DB_NAME') as Base_Datos, SUBSTR(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'),1,20) esquema, SUBSTR(SYS_CONTEXT('USERENV', 'HOST'), 1,20) Nombre_PC, SUBSTR(SYS_CONTEXT('USERENV', 'OS_USER'),1,30) Usuario_SO, SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'),1,20) Usuario_BD, TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FECHA	FROM V$INSTANCE;

--*** TRANCODE BillPaymentPSEBillPmt  P_BILLPAYPSEPMT Debito del pago PSE hacia las Entidades

-- Codigos de error Banco Avvillas
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','0','0','P_BILLPAYPSEPMT',NULL,'0','Transacción Exitosa');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','0','00','P_BILLPAYPSEPMT',NULL,'0','Transacción Exitosa');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','0','90','P_BILLPAYPSEPMT',NULL,'0','Transacción Exitosa');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1420','1','P_BILLPAYPSEPMT',NULL,'1','Acceso no autorizado.  Por favor comuníquese con la Entidad');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2080','2','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. El valor de la transacción es superior al tope máximo establecido.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','3000','3','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Excede los límites autorizados.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','200','4','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1050','5','P_BILLPAYPSEPMT',NULL,'1','Valor invalido');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1050','11','P_BILLPAYPSEPMT',NULL,'1','Valor invalido');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','401','12','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción. Comuníquese con la entidad');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1050','13','P_BILLPAYPSEPMT',NULL,'1','Valor invalido');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2300','14','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Cuenta origen inválida. Comuníquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1220','15','P_BILLPAYPSEPMT',NULL,'1','Número de obligación o de factura inválido o no existe.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1400','16','P_BILLPAYPSEPMT',NULL,'1','La factura esta vencida o tiene restricciones de pago');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1380','17','P_BILLPAYPSEPMT',NULL,'1','Este pago ya fue realizado.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2350','19','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1360','29','P_BILLPAYPSEPMT',NULL,'1','En este momento no es posible procesar su transacción - Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1360','30','P_BILLPAYPSEPMT',NULL,'1','En este momento no es posible procesar su transacción - Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1360','31','P_BILLPAYPSEPMT',NULL,'1','En este momento no es posible procesar su transacción - Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','200','32','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1220','33','P_BILLPAYPSEPMT',NULL,'1','Número de obligación o de factura inválido o no existe.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1056','42','P_BILLPAYPSEPMT',NULL,'1','OTP invalida o anulada por reintentos fallidos.  Solicite una nueva OTP.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2940','51','P_BILLPAYPSEPMT',NULL,'1','Fondos insuficientes');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','3300','61','P_BILLPAYPSEPMT',NULL,'1','El número de pagos es inválido. Por favor intente nuevamente.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2350','62','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2080','63','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. El valor de la transacción es superior al tope máximo establecido.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1400','70','P_BILLPAYPSEPMT',NULL,'1','La factura esta vencida o tiene restricciones de pago');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1050','71','P_BILLPAYPSEPMT',NULL,'1','Valor invalido');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1360','72','P_BILLPAYPSEPMT',NULL,'1','En este momento no es posible procesar su transacción - Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1360','73','P_BILLPAYPSEPMT',NULL,'1','En este momento no es posible procesar su transacción - Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','3040','74','P_BILLPAYPSEPMT',NULL,'1','El monto de la obligación  no concuerda con el valor a pagar.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1056','96','P_BILLPAYPSEPMT',NULL,'1','OTP invalida o anulada por reintentos fallidos.  Solicite una nueva OTP.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','700','99','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','310','98','P_BILLPAYPSEPMT',NULL,'1','Transacción en proceso. Por favor verifique mas tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','200','9091','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - datos inconsistentes. Comuníquese con la Entidad.');


INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1400' ,'10','P_BILLPAYPSEPMT',NULL,'1','La factura esta vencida o tiene restricciones de pago');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'-12','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'20','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','310'  ,'21','P_BILLPAYPSEPMT',NULL,'1','Transacción en proceso. Por favor verifique mas tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'22','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'23','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'24','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'25','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'27','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'28','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'34','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2400' ,'35','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'40','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1600' ,'41','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','1055' ,'42','P_BILLPAYPSEPMT',NULL,'1','OTP invalida por vencimiento o anulación.  Solicite una nueva OTP.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'43','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2350' ,'44','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. La cuenta origen está restringida. Comuníquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'45','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'46','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','3320' ,'52','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Excede los límites autorizados. Comuníquese con la Entidad');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'53','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'54','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'55','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'56','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'57','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','300'  ,'58','P_BILLPAYPSEPMT',NULL,'1','No es posible procesar la transacción - Problemas técnicos. Por favor intente más tarde.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1,'00010524','2300' ,'6','P_BILLPAYPSEPMT',NULL,'1','Transacción rechazada. Cuenta origen inválida. Comuníquese con la entidad.');

INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '2667', 'P_BILLPAYPSEPMT', NULL, '1', 'Error al abrir Cola - Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '2666', 'P_BILLPAYPSEPMT', NULL, '1', 'Error al abrir Cola - Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '300', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente - TimeOut');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', 'env:Server', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', 'env:Client', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '700', '700', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el WSRR');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '200', '200', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion - datos inconsistentes. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '400', '400', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5025', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5004', 'P_BILLPAYPSEPMT', NULL, '1', 'No es posible procesar la transaccion. Comuniquese con la Entidad.');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '710', '710', 'P_BILLPAYPSEPMT', NULL, '1', 'Error en Base de Datos');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '3701', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '300', '3151', 'P_BILLPAYPSEPMT', NULL, '1', 'Error de conexion con el cliente - TimeOut');
INSERT INTO MAPPING_CODE(ID, BANKID, IFXCODE, HOSTCODE, TRANCODE, ACCTTYPEHOSTID, ERROR, DESC_ERROR_HOM) VALUES((SELECT MAX(ID) FROM MAPPING_CODE) + 1, '00010524', '600', '5025', 'P_BILLPAYPSEPMT', NULL, '1', 'Error validacion estructura');

INSERT INTO CUSTIDTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM CUSTIDTYPE) + 1,'00010524', '1', 'C', 'P_BILLPAYPSEPMT', 'Cedula Ciudadania');
INSERT INTO CUSTIDTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM CUSTIDTYPE) + 1,'00010524', '5', 'R', 'P_BILLPAYPSEPMT', 'Registro Civil');
INSERT INTO CUSTIDTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM CUSTIDTYPE) + 1,'00010524', '6', 'N', 'P_BILLPAYPSEPMT', 'NIT Persona natural');
INSERT INTO CUSTIDTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM CUSTIDTYPE) + 1,'00010524', '4', 'T', 'P_BILLPAYPSEPMT', 'Pasaporte');
INSERT INTO CUSTIDTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM CUSTIDTYPE) + 1,'00010524', '2', 'E', 'P_BILLPAYPSEPMT', 'Cedula Extranjeria');

INSERT INTO ACCTTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM ACCTTYPE) + 1, '00010524','1', '1','P_BILLPAYPSEPMT', 'Cuenta de Ahorros');
INSERT INTO ACCTTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM ACCTTYPE) + 1, '00010524','2', '0','P_BILLPAYPSEPMT', 'Cuenta de Ahorros');
INSERT INTO ACCTTYPE (ID, BANKID, EPID, HOSTID, TRANCODE, DESCRIPTION)VALUES((SELECT MAX(ID) FROM ACCTTYPE) + 1, '00010524','6', '6','P_BILLPAYPSEPMT', 'Cuenta Corriente');
COMMIT;